// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVrlxKZXqoPZqMqGGXYB4f8zB_L3H6JN8',
    appId: '1:234966669188:web:d6e84234d2582fc47f2fd1',
    messagingSenderId: '234966669188',
    projectId: 'hospitalsystem-de126',
    authDomain: 'hospitalsystem-de126.firebaseapp.com',
    storageBucket: 'hospitalsystem-de126.appspot.com',
    measurementId: 'G-2E54DMQSBW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRcSWQ1ygOUHL0LS0CC6dYwkq1uSirIBQ',
    appId: '1:234966669188:android:d11d7d6c92ae159d7f2fd1',
    messagingSenderId: '234966669188',
    projectId: 'hospitalsystem-de126',
    storageBucket: 'hospitalsystem-de126.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0iBJQx5f8b81GGCeLhrz7TfTXCSs9BMU',
    appId: '1:234966669188:ios:f2dd0a110c80a3d37f2fd1',
    messagingSenderId: '234966669188',
    projectId: 'hospitalsystem-de126',
    storageBucket: 'hospitalsystem-de126.appspot.com',
    iosClientId: '234966669188-cocqs3iqc8lp7fro68fpg9hngkkl19ku.apps.googleusercontent.com',
    iosBundleId: 'com.example.hospitalSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0iBJQx5f8b81GGCeLhrz7TfTXCSs9BMU',
    appId: '1:234966669188:ios:f2dd0a110c80a3d37f2fd1',
    messagingSenderId: '234966669188',
    projectId: 'hospitalsystem-de126',
    storageBucket: 'hospitalsystem-de126.appspot.com',
    iosClientId: '234966669188-cocqs3iqc8lp7fro68fpg9hngkkl19ku.apps.googleusercontent.com',
    iosBundleId: 'com.example.hospitalSystem',
  );
}
